### PR TITLE
feat: fallback to installed npm package

### PR DESCRIPTION
**Pull request by kevinmarrec**
# Feature

```ts
export default {
  extends: ['@awesome/package']
}
```

can extends `@awesome/package` defined this way :

```json
{
  "exports": {
    ".": "./config.ts"
  },
  "main": "./config.ts"
}
```

# TODO

- [ ] Tests - Requires to publish some npm package that contains just a config file ?

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for PR @kevinmarrec but can you please explain better why this would be a useful case to use a non standard config name?

**Comment by kevinmarrec** [comment]
@pi0 The issue is that the package `main` field may be in a nested directory, let's say `dist` for example. And as `jiti.resolve` will get this resolved file, it's pretty hard to get the package root, isn't it ?

Depending on if the user use `npm`/`yarn` or `pnpm`, it may result in even trickier resolved path.

I don't know what is the best solution to have the "package" behavior, but I think we shouldn't have to do `'./node_modules/@awesome/package'` to extends it.

**Comment by pi0** [comment]
If the package's main entry is a theme and points to `dist/inex.js`, it should contain theme in `dist/config.js` as well. If it is a general library or module with a theme included, we can use `exports: { theme: './theme' }` to a directory containing the base and extend as `@awesome/package/theme`)

I believe it should be identical. We can move your solution `const configFile = jiti.resolve(source)` to before `isDir` check to try resolving as module if path is not absolute neither relative (dir). It can make implementation much simpler :)

**Comment by kevinmarrec** [comment]
Makes sense !

We'll need to create a package which includes a theme, and install it here as dev dependency, to be able to properly write a test for this scenario.

**Comment by DemoMacro** [comment]
This is exactly the FEAT I was looking for!

**Comment by pi0** [comment]
Added feature via 7c48947754bce2f881d153eb3c490f2940814c80

**Pull request closed without merging**
